CREATE DATABASE IF NOT EXISTS the_shelf;
USE the_shelf;
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(150) NOT NULL,
    cover LONGTEXT,
    rating INT DEFAULT 0,
    review TEXT,
    dateAdded BIGINT NOT NULL
);
DESCRIBE books;